### ISSUE TITLE
Hierarchical key structure when storing metadata

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#103]
@hyokyungk 한 번 검토를 부탁드립니다. 😊

**What would you like to be enhanced**
: 

현재 CB-Bridge에서는
Cloud-Barista의 K8s 모드에서
각 FW (SP, TB, LB, DF 등) 가 nutsdb에 저장하던 metadata를
단일 etcd에 저장하는 것으로 변경 고려/진행 중에 있습니다. ([관련 discussion](https://github.com/cloud-barista/cb-operator/discussions/139))

이에 각 FW가 Key-Value storing 시 활용하고 있는 Key structure를 조사해 보니
CB-Dragonfly는
key space 의 root 에
- `agentlist` (slash로 시작하지 않음)
- `{agentUUID}` (상동)
- `delTopics/{topic}`
- `{eventLog.Id}`
- `config/{key}`
- `collectorGroupTopic/{collectorIdx}`
- `topic/{topic}`

등의 key를 만들고 있습니다.
(관련 표: https://github.com/cloud-barista/cb-operator/discussions/139#discussioncomment-982901)

이들이 좀 더 정돈되면서도 Hierarchical structure 를 가지면 좋을 것 같습니다.

**Why is this needed**
: 

**Proposed solution**
:

(제가 Dragonfly 의 data's logical relation/hierarchy/structure 를 잘 몰라서, 아래 예시가 적절하지 않을 수 있습니다.)

예:
- /monitoring/agents/{agentID}
- /monitoring/collectors/{collectorID}
- /monitoring/topics/{topicID}
- (TB에 의해 생성된 /ns/{nsId}/mcis/{mcisId}/vm/{vmId} 키 아래에
/ns/{nsId}/mcis/{mcisId}/vm/{vmId}/metrics/{metric} 과 같이 추가하는 방법도 있겠으나
적절할지는 모르겠습니다.)
- ...

**Comment by hyokyungk** [comment]
@jihoon-seo 

기존 CB-Store에서는 etcd와 다르게 key 값이 hierarchy 하게 존재하는 경우 목록 조회가 불가능했습니다.
따라서 별도의 개별 key를 통해 메타데이터를 관리하고 있습니다.
해당 부분은 사용하고 있는 CB-Store 부분과 key 매핑 부분을 다시 검토 후에 의견 전달드리도록 하겠습니다.

**Comment by jihoon-seo** [comment]
@hyokyungk 그렇군요 😊

> 기존 CB-Store에서는 etcd와 다르게 key 값이 hierarchy 하게 존재하는 경우 목록 조회가 불가능했습니다.
(ex. /agent/{UUID} 로 key 설정 후 /agent 목록 조회 불가)

@powerkimhub 님의 말에 따르면
etcd 에는 key 들을 포함할 수 있는 directory 개념이 있는데
nutsdb 에는 directory 개념이 없다고 합니다.
그래서 위의 이슈가 있는 것이 아닐까 추정됩니다.

---

CB-Tumblebug 에서는 어떻게 하고 있는지 찾아 보니 다음과 같이 되어 있습니다. 😊

[`func ListResource()`](https://github.com/cloud-barista/cb-tumblebug/blob/7a15300e497b4883cdb263b2f166000d981c7318/src/core/mcir/common.go#L731-L732)

```Go
	keyValue, err := common.CBStore.GetList(key, true)
	keyValue = cbstore_utils.GetChildList(keyValue, key)
```

**Comment by hyokyungk** [comment]
@jihoon-seo 

자세하게 가이드 주셔서 감사합니다.
CB-Tumblebug에서 활용되는 방식 기준으로 제안해주신 CB-Store key 매핑 관련 리팩토링을 검토해보도록 하겠습니다.

**Comment by inno-cloudbarista** [comment]
@jihoon-seo 

```
예:

/monitoring/agents/{agentID}
/monitoring/collectors/{collectorID}
/monitoring/topics/{topicID}
(TB에 의해 생성된 /ns/{nsId}/mcis/{mcisId}/vm/{vmId} 키 아래에
/ns/{nsId}/mcis/{mcisId}/vm/{vmId}/metrics/{metric} 과 같이 추가하는 방법도 있겠으나
적절할지는 모르겠습니다.)
```
예시로 전달해주셨던 hierarchy 키 구조를 참고해서 cb-store 키 들을 변경했습니다.
키 정보
```
const (
	Agent                        = "/monitoring/agents"
	MonConfig                = "/monitoring/configs"
	Topic                         = "/monitoring/topics"
	CollectorGroupTopic = "/monitoring/collectorGroupTopics"
	DeleteTopic               = "/monitoring/delTopics"
	EventLog                  = "/monitoring/eventLogs"
)
```

해당 커밋: https://github.com/inno-cloudbarista/cb-dragonfly/commit/8c586a32954843b25ef9779a2e87594f998f83cc

@jihoon-seo  검토 후 타 FW와 키 구조가 통일되었다고 판단되면, feature/cbstore 브랜치 코드를 PR할 예정입니다.
검토 부탁드리겠습니다.
