### ISSUE TITLE
`Store.Put()` vs. `StorePut()`

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#104]
DF 소스에서

대부분 `cbstore.GetInstance().StorePut()` 함수를 활용하는데 (reference: 18개)

`cbstore.GetInstance().Store.Put()` 함수를 활용하는 reference가 1개 있습니다.

`cb-dragonfly/pkg/core/agent/metadata.go`
```Go
func (a AgentListManager) putAgentListToStore(agentList map[string]AgentInfo) error {
	agentListBytes, err := json.Marshal(agentList)
	if err != nil {
		return errors.New(fmt.Sprintf("failed to convert agentList format to json, error=%s", err))
	}
	err = cbstore.GetInstance().Store.Put(AgentListKey, string(agentListBytes))
	if err != nil {
		return errors.New(fmt.Sprintf("failed to put agentList, error=%s", err))
	}
	return nil
}
```

이것이 의도된 것인지 아니면 일관성을 맞춰야 하는 것인지 문의드립니다. 😊

**Comment by hyokyungk** [comment]
@jihoon-seo 

**GET, PUT, DELET 등 CB-Store 관련 동작 처리 시 CB-Dragonfly에서 별도 예외처리 하는 부분이 생겼을 때, 공통적으로 처리하기 위해서 StoreXXX() 형식으로 wrapping 처리를 했습니다.**
CB-Dragonfly FW에서 CB-Store 사용 통일성을 지키기 위해서, 해당 부분은 StorePut 함수로 처리가 필요할 것 같습니다.
(해당 부분은 CB-Dragonfly에서 활용되는 CB-Store 통일성을 위한 것으로, 함수 기능 및 동작에서는 영향을 주지 않습니다.)

[참고]

cbstore.go 파일
```
func (cs *CBStore) StorePut(key string, value string) error {
	return cs.Store.Put(key, value)
}
func (cs *CBStore) StoreGet(key string) string {
	keyVal, _ := cs.Store.Get(key)
	if keyVal == nil {
		return ""
	}
	return keyVal.Value
}
```
