### ISSUE TITLE
Config: YAML vs. env var

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#13]
안녕하세요
설정 파일 관련하여 이슈를 올립니다.

CB-Store 에도 올렸던 이슈인데요
( https://github.com/cloud-barista/cb-store/issues/14 )

현재 Dragonfly 의 환경설정은 `conf/config.yaml` 파일로 하도록 되어 있습니다.

올려 주신 Dockerfile 로 이미지를 만들었는데
(`docker build --tag cloudbaristahub/cb-dragonfly:v0.1-20200327 .`)

설정 파일에 `{{influxdb_ip}}`, `{{password}}` 등을 수정하지 않고 이미지를 만들어서 그런지

컨테이너 실행 (`docker run -p 8094:8094 --name cb-dragonfly cloudbaristahub/cb-dragonfly:v0.1-20200327`) 시 에러가 납니다.

```
panic: yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into string
  line 17: cannot unmarshal !!map into string

goroutine 1 [running]:
main.main()
        /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/main/main.go:35 +0x54e
```

호스트 머신에 올바른 `config.yaml` 을 두고
컨테이너 실행 시 `-v` 옵션으로 마운트하는 방법이 있긴 한데요

향후 docker-compose, Helm chart 등의 방식으로 deploy 하는 것을 고려하면
이는 적절한 방법이 아닌 것 같다는 생각이 들기는 합니다.

혹시, 환경 설정 항목들을 env var 형태로 받는 것에 대해서는 어떻게 생각하시는지 문의를 드립니다.

Ref: @powerkimhub @seokho-son

**Comment by hyokyungk** [comment]
@jihoon-seo
Ref: @powerkimhub @seokho-son @kyongminkwon 

먼저, 개선 사항에 대해 의견 주셔서 감사합니다.
도커 실행 시 에러가 발생하지 않도록 {{IP}} 형태로 처리된 부분을 일괄적으로 127.0.0.1로 변경했습니다.
(참조 커밋 : [1fc8d5fdfe88ee661c064ffcc52d1098bcb04d21](https://github.com/cloud-barista/cb-dragonfly/commit/1fc8d5fdfe88ee661c064ffcc52d1098bcb04d21))

내부 테스트 결과 컨테이너 재시작 시 ENV 변수가 삭제되는 경우가 있어서,
해당 이슈를 고려해 현재는 config.yaml 파일을 기준으로 작업하도록 개발이 되어있습니다.

추후 로직에는
 (1) ENV 환경변수가 지정이 되어있을 경우 해당 변수 값을 우선순위로 설정하고,
 (2) 만약 ENV 환경변수가 지정이 되어있지 않다면 config.yaml  파일에 설정된 변수 값으로 설정할 예정입니다.

해당 작업이 반영이 완료되면 다시 #13 이슈를 통해 공유드리도록 하겠습니다.
