### ISSUE TITLE
AWS, Ubuntu 18.04 VM에 대해 "failed to change telegraf permission" 에러 발생

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#138]
**What happened**
: 

[AWS VM 정보]
- Region: Ohio (us-east-2)
- Image: ami-01e7ca2ef94a0ae86 (amazon/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20210224)
- Spec: t2.micro

[Agent install request body]
POST `http://localhost:9090/dragonfly/agent`
```json
{
  "ns_id": "ns01",
  "mcis_id": "jhseo",
  "vm_id": "aws-us-east-2-1",
  "public_ip": "18.219.61.250",
  "port": "22",
  "user_name": "cb-user",
  "ssh_key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----",
  "cspType": "aws",
  "service_type": "vm"
}
```

[Agent install response body]
```json
{
  "message": "failed to change telegraf permission, err=Process exited with status 1"
}
```

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
  - CB-Spider 최신버전 (f09c6c3, Fri Oct 21 20:11:55 2022 +0900)
  - CB-Tumblebug 최신버전 (5b53b8c, Mon Oct 24 17:43:32 2022 +0900, 
    PR cloud-barista/cb-tumblebug#1239 머지 이후)
  - CB-Dragonfly 최신버전
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:
(CC @powerkimhub : "GusetOS 확장 지원 검증 시험" 중 발생한 이슈입니다.)

**Comment by Jin-Whee-Park** [comment]
안녕하세요. @jihoon-seo @powerkimhub 
문의 주신 환경 기준으로 테스트 결과 공유드립니다.

**[AWS VM 정보]**

- Region: Ohio (us-east-2)
- Image: ami-01e7ca2ef94a0ae86 (amazon/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20210224)
- Spec: t2.micro

**[CB-DF 정보]**
- 구동 환경: docker-compose
- 버전 정보: 0.6.9

**[테스트 결과]**
- 에이전트 설치: 정상
- PUSH 모니터링 메트릭 수집: 정상



**[관련 이미지]**
1. Spider Admin 웹 기반 VM 생성
![스크린샷, 2022-11-08 09-56-21](https://user-images.githubusercontent.com/51406068/200448093-dfa1cb62-f7e6-4777-9758-4cf6a2841e28.png)

2. Postman 기반 Agent 설치
![스크린샷, 2022-11-08 09-56-02](https://user-images.githubusercontent.com/51406068/200448278-c56c371b-b8bd-406f-95f5-f4da98f08cd4.png)


3. DF 모니터링 메트릭 수집 로그
![스크린샷, 2022-11-08 09-56-13](https://user-images.githubusercontent.com/51406068/200448293-e86e7a54-3f31-44fd-b118-218b9d43494a.png)

4. AWS VM 배포 현황
![스크린샷, 2022-11-08 09-56-36](https://user-images.githubusercontent.com/51406068/200448327-3808b0d1-dbe2-478b-b986-b674ef1dd565.png)

5. Chronograf 기반 수집 결과
![스크린샷, 2022-11-08 10-02-35](https://user-images.githubusercontent.com/51406068/200448437-730fec5e-2ff8-41a0-8db1-d00803bb2f3b.png)

**Comment by jihoon-seo** [comment]
@Jin-Whee-Park 님 및 @seokho-son 님 환경에서는 재현이 안 되는 것으로 보아, 아무래도 제 환경 (DF 실행 방법 등) 이슈일 가능성이 있을 것 같습니다. 😥
이 이슈는 제가 close 처리 하도록 하겠습니다.. ㅎㅎ
