### ISSUE TITLE
Should NS be included in Dragonfly REST API path?

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#31]
@seokho-son @powerkimhub 

According to https://github.com/cloud-barista/cb-tumblebug/pull/203,

one should call Dragonfly REST API like this:

```Shell
curl -sX GET http://localhost:9090/dragonfly/mcis/aws-us-east-1-shson/vm/aws-us-east-1-shson-01/metric/cpu/rt-info?statisticsCriteria=max
```

---

But the logical hierarchy of NS, MCIS, and VM (in Tumblebug) is like this:
- NS
  - MCIS
    - VM

---

How about this option?
```Shell
curl -sX GET http://localhost:9090/dragonfly/ns/my-namespace/mcis/aws-us-east-1-shson/vm/aws-us-east-1-shson-01/metric/cpu/rt-info?statisticsCriteria=max
```

**Comment by powerkimhub** [comment]
@jihoon-seo  @seokho-son @hyokyungk 

powerkimhub 의견입니다. 

- NS 추가 동의합니다
  - 사유: NS 이름이 다르면 MCIS 이름이 동일할 수 있습니다. NS 이름이 없다면 이 둘을 구분할 수 없습니다.

**Comment by hyokyungk** [comment]
@jihoon-seo @seokho-son @powerkimhub 

CB-Tumblebug 클라우드 리소스 hirerachy에 맞춰 REST API 규격 수정하도록 하겠습니다.
( NS / MCIS / VM depth 기준으로 적용 예정)

**Comment by hyokyungk** [comment]
@jihoon-seo @seokho-son @powerkimhub 

[API 목록]
- 멀티 클라우드 인프라 서비스 모니터링 **(기능 미구현 / 형상만 정의)**
    - 모니터링 조회
        - [GET] /dragonfly/ns/:ns/mcis/:mcis_id/info
    - 실시간 모니터링 조회
        - [GET] /dragonfly/ns/:ns/mcis/:mcis_id/rt-info
- 멀티 클라우드 인프라 서비스 가상머신 모니터링
    - 모니터링 조회
        - [GET] /dragonfly/ns/:ns/mcis/:mcis_id/vm/:vm_id/metric/:metric_name/info
    - 실시간 모니터링 조회
        - [GET] /dragonfly/ns/:ns/mcis/:mcis_id/vm/:vm_id/metric/:metric_name/rt-info

#34 
ns 프로퍼티를 REST API 공통 규격에 일괄적으로 추가했습니다.
현재 feature/grpc 브랜치에만 반영한 내용으로, gRPC 작업이 끝난 후 master 브랜치에 적용할 예정입니다.
