### ISSUE TITLE
Spider, TB 의 API 변경에 대한 대응

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#5]
- 관련 Issue
  - Suggestion: Add `/spider/` prefix for REST APIs https://github.com/cloud-barista/cb-spider/issues/139
  - Suggestion: Add `/tumblebug/` prefix for REST APIs https://github.com/cloud-barista/cb-tumblebug/issues/96
- 관련 PR/commit
  - Apply changes for API prefix addition of Spider and TB https://github.com/cloud-barista/cb-tumblebug/pull/98

---

![CB-Spider - -2020 03 11](https://user-images.githubusercontent.com/46767780/76602355-173dc500-654e-11ea-844d-17eafdae8b3c.png)

**Comment by powerkimhub** [comment]
<변경사항>
  ![image](https://user-images.githubusercontent.com/46367962/76719036-ecd14f00-677b-11ea-8c5f-bee44bf663e9.png)

**Comment by jihoon-seo** [comment]
현재 CB-Dragonfly 모듈의 경우 별도로 CB-Spider, CB-Tumblebug API를 호출하지 않는다고 합니다.
이 이슈는 close 하겠습니다.
추후 Dragonfly 에서 Spider, Tumblebug 의 API 를 호출하게 되면, 위의 사항을 참고하시면 되겠습니다.
