### ISSUE TITLE
Remove cb-dragonfly binary file from repo

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#66]
현재 `cb-dragonfly/bin/` 에 cb-dragonfly binary file 이 존재합니다.

혹시 잘못 올라간 것이라면 / 꼭 필요한 것이 아니라면, repo 에서 삭제하고 `.gitignore` 에 추가하는 것이 어떨까요? ^^

**Comment by hyokyungk** [comment]
@jihoon-seo 

이슈로 올려주신 내용을 확인해 본 결과 별도로 정리가 가능한 파일로 확인했습니다.
이슈에 올려주신대로, repo에서 삭제처리 후 gitignore 파일에 bin 폴더를 추가로 등록했습니다.

#67 에 해당 내용이 적용되었으니, 참고 부탁드립니다.

**Comment by jihoon-seo** [comment]
@hyokyungk 
비슷한 건으로, 다음의 파일도 있습니다.
한 번 확인을 부탁 드립니다.. ^^

- [./pkg/cmd/cbmoncli](https://github.com/cloud-barista/cb-dragonfly/blob/master/pkg/cmd/cbmoncli): Executable File  27.8 MB

CC: @powerkimhub

**Comment by jihoon-seo** [comment]
- Resolved by #72
