### ISSUE TITLE
Apply cloud-barista common Readme badge

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-dragonfly#82]
안녕하세요. Cloud-Barista 커뮤니티 차원에서 

각 FW 저장소의 Readme 개선에 대한 논의가 있었습니다.

- Readme에 Badge를 추가하여, 저장소 꾸미기

다음 링크를 확인하셔서, Readme 업데이트를 요청드립니다.. ^^

https://github.com/cloud-barista/docs/wiki/Common-badges-for-readme-for-Cloud-Barista-repos

**Comment by seokho-son** [comment]
PTAL @hyokyungk :)

**Comment by hyokyungk** [comment]
@seokho-son 

https://github.com/cloud-barista/cb-dragonfly/commit/0cfa9e75b0eae6ee612088cd8f696d38008c473e
해당 커밋에 README 뱃지 적용 코드를 반영했습니다.
다만, cb-tumblebug 리포와 다르게 빌드의 status 정보가 정상적으로 가져오지 않고 있는 것 같습니다

**Comment by seokho-son** [comment]
@hyokyungk 빠른 반영 감사합니다.. 🥇 

제가 #84 로 테스트해보니
현재 빌드 워크플로우가, *.md 파일인 경우에 스킵하고 있어서,
마지막 수정 사항이었던 readme.md 변경시 빌드를 수행하지 않았네요..^^
그래서 상태 없음으로 나온 듯 합니다.

go 코드 수정시에는 빌드 처리 여부가 정상적으로 잘 나오는 것 같습니다. PR 참고 하시기 바랍니다.

**Comment by hyokyungk** [comment]
@seokho-son 

#84 PR 기반으로 최신 build가 pass 상태인 것을 확인했습니다.
#85 PR 도 머지 완료했으니, cb-dragonfly repo에는 cloud-barista 뱃지 적용이 완료된 상태입니다.

해당 이슈는 클로징 하도록 하겠습니다
