### ISSUE TITLE
CB-Dragonfly의  모니터링 정책이 Push 일 경우 정상 동작하지 않음

### ISSUE THREAD

**Issue by pjhmong** [cloud-barista/cb-dragonfly#90]
모니터링 정책을 push로 설정할 경우 kafka 전체 토픽 메시지 조회 로직 오동작

**Comment by jihoon-seo** [comment]
이 이슈는 PR #91 에 의해 해결된 것으로 보입니다.

**Comment by hyokyungk** [comment]
@jihoon-seo 
cc @pjhmong 

해당 부분은 해결된 버그로 클로징 처리를 하도록 하겠습니다.
